const crypto = require('crypto')
const env = require('../config/env')
const { generateToken } = require('../utils/jwt.util')
const { User, ROLES } = require('../models/User')
const { DemoSession, DEMO_STATUS } = require('../models/DemoSession')
const { DemoState } = require('../models/DemoState')
const { getIO } = require('./socket.service')

// In-memory cache for ultra-low latency middleware verification
let cachedDemoGeneration = null
// In-memory store for active QR URL so Super Admin page refresh can display current QR without storing plaintext in DB
let currentActiveDemoToken = null

/**
 * Computes SHA-256 hash of a raw token string.
 * Plaintext secrets are never stored in the database.
 *
 * @param {string} token
 * @returns {string} Hex encoded sha256 hash
 */
function hashDemoToken(token) {
  if (!token || typeof token !== 'string') {
    throw new Error('Token must be a valid non-empty string for hashing.')
  }
  return crypto.createHash('sha256').update(token.trim()).digest('hex')
}

/**
 * Retrieves the current global demo session generation version.
 * Hits memory cache first; falls back to MongoDB.
 *
 * @returns {Promise<number>} Current generation integer
 */
async function getCurrentDemoGeneration() {
  if (cachedDemoGeneration !== null && typeof cachedDemoGeneration === 'number') {
    return cachedDemoGeneration
  }

  let state = await DemoState.findOne({ key: 'GLOBAL_DEMO_STATE' })
  if (!state) {
    state = await DemoState.create({
      key: 'GLOBAL_DEMO_STATE',
      currentGeneration: 1,
    })
  }

  cachedDemoGeneration = state.currentGeneration
  return cachedDemoGeneration
}

/**
 * Updates memory cache for current generation.
 *
 * @param {number} newGen
 */
function invalidateGenerationCache(newGen) {
  cachedDemoGeneration = newGen
}

/**
 * Finds or lazily provisions the anchor Demo Student user identity.
 * Avoids creating unbounded student records on every QR scan.
 *
 * @returns {Promise<import('../models/User').User>}
 */
async function getOrCreateDemoStudent() {
  let demoUser = await User.findOne({ email: 'demo-student@smartclassroom.edu' })
  if (!demoUser) {
    // Generate a secure unguessable random password hash for the anchor demo user
    const randomPassword = crypto.randomBytes(32).toString('hex')
    const passwordHash = await User.hashPassword(randomPassword)

    demoUser = await User.create({
      name: 'Demo Student',
      email: 'demo-student@smartclassroom.edu',
      passwordHash,
      role: ROLES.STUDENT,
      department: 'Computer Science',
      assignedClasses: ['Classroom 101', 'IoT Lab'],
      isActive: true,
    })
    console.log('[DemoAuth] 🎓 Created anchor Demo Student user identity:', demoUser.email)
  }
  return demoUser
}

/**
 * Generates a brand new temporary demo QR credential.
 *
 * @param {Object} adminUser - Authenticated Super Admin user object
 * @returns {Promise<Object>} QR credentials (does NOT include tokenHash)
 */
async function generateDemoCredential(adminUser) {
  const currentGen = await getCurrentDemoGeneration()

  // Generate cryptographically secure 256-bit random token
  const rawToken = crypto.randomBytes(32).toString('hex')
  const tokenHash = hashDemoToken(rawToken)
  const tokenPrefix = rawToken.slice(0, 8)

  const expiryMinutes = env.DEMO_QR_EXPIRY_MINUTES || 120
  const expiresAt = new Date(Date.now() + expiryMinutes * 60 * 1000)

  // Invalidate any previously pending active tokens for this generation to ensure single-active-token clarity
  await DemoSession.updateMany(
    { generation: currentGen, isActive: true },
    { $set: { isActive: false, status: DEMO_STATUS.REVOKED, revokedAt: new Date(), revokedBy: adminUser._id } }
  )

  const session = await DemoSession.create({
    tokenHash,
    tokenPrefix,
    generation: currentGen,
    isActive: true,
    status: DEMO_STATUS.ACTIVE,
    expiresAt,
    createdBy: adminUser._id,
    scanCount: 0,
  })

  // Update pointer in DemoState
  await DemoState.findOneAndUpdate(
    { key: 'GLOBAL_DEMO_STATE' },
    { $set: { activeSessionId: session._id } },
    { upsert: true }
  )

  const baseUrl = env.DEMO_QR_BASE_URL || 'http://localhost:5173'
  const qrUrl = `${baseUrl.replace(/\/+$/, '')}/demo-login/${rawToken}`

  // Cache in memory for immediate display on status check
  currentActiveDemoToken = {
    token: rawToken,
    qrUrl,
    generation: currentGen,
    expiresAt,
  }

  try {
    const io = getIO()
    if (io) {
      io.emit('demo:status_changed', {
        reason: 'GENERATED',
        generation: currentGen,
        expiresAt,
        timestamp: new Date().toISOString(),
      })
    }
  } catch {}

  console.log(
    `[DemoAuth] 🎫 Demo QR generated by admin (${adminUser.email}): Gen=${currentGen}, Prefix=${tokenPrefix}..., Expiry=${expiresAt.toISOString()}`
  )

  return {
    qrUrl,
    token: rawToken,
    tokenPrefix: `${tokenPrefix}...`,
    generation: currentGen,
    expiresAt,
    expiresInMinutes: expiryMinutes,
    status: DEMO_STATUS.ACTIVE,
    isActive: true,
    scanCount: 0,
    createdAt: session.createdAt,
  }
}

/**
 * Validates a scanned QR token and issues a temporary student session JWT.
 *
 * @param {string} rawToken - Scanned temporary token
 * @param {Object} [meta={}] - Request metadata for auditing (ip, userAgent)
 * @returns {Promise<Object>} Token, user details, and expiry
 */
async function loginWithDemoToken(rawToken, meta = {}) {
  if (!rawToken || typeof rawToken !== 'string' || rawToken.trim() === '') {
    const error = new Error('Demo login token is required.')
    error.code = 'TOKEN_REQUIRED'
    error.statusCode = 400
    throw error
  }

  const tokenHash = hashDemoToken(rawToken.trim())

  // Look up session by token hash
  const session = await DemoSession.findOne({ tokenHash })
  if (!session) {
    const error = new Error('Invalid demo QR token.')
    error.code = 'INVALID_DEMO_TOKEN'
    error.statusCode = 401
    throw error
  }

  // Check if session is revoked or inactive
  if (!session.isActive || session.status !== DEMO_STATUS.ACTIVE) {
    const error = new Error('This demo QR credential has been revoked or reset. Please scan a new QR code.')
    error.code = 'DEMO_TOKEN_REVOKED'
    error.statusCode = 401
    throw error
  }

  // Check generation match
  const currentGen = await getCurrentDemoGeneration()
  if (session.generation !== currentGen) {
    const error = new Error('This demo QR credential belongs to an outdated demonstration version. Please scan the current QR code.')
    error.code = 'DEMO_GENERATION_MISMATCH'
    error.statusCode = 401
    throw error
  }

  // Check expiry
  if (session.expiresAt <= new Date()) {
    session.isActive = false
    session.status = DEMO_STATUS.EXPIRED
    await session.save()

    const error = new Error('This demo QR credential has expired. Please ask the administrator for a new QR code.')
    error.code = 'DEMO_TOKEN_EXPIRED'
    error.statusCode = 401
    throw error
  }

  // Increment scan count and record scan timestamp
  session.scanCount = (session.scanCount || 0) + 1
  session.lastScannedAt = new Date()
  await session.save()

  // Ensure anchor student identity exists
  const demoStudent = await getOrCreateDemoStudent()

  // Compute remaining validity duration
  const remainingMinutes = Math.max(
    1,
    Math.round((session.expiresAt.getTime() - Date.now()) / (1000 * 60))
  )

  // Mint temporary authenticated JWT tagged with authType = 'DEMO_QR'
  const jwtPayload = {
    id: demoStudent._id.toString(),
    role: ROLES.STUDENT,
    authType: 'DEMO_QR',
    isDemo: true,
    demoGeneration: session.generation,
  }

  const jwtToken = generateToken(jwtPayload, `${remainingMinutes}m`)

  console.log(
    `[DemoAuth] 📱 Demo student session created: Gen=${session.generation}, Scans=${session.scanCount}, IP=${meta.ip || 'unknown'}`
  )

  return {
    token: jwtToken,
    user: {
      id: demoStudent._id,
      name: demoStudent.name,
      email: demoStudent.email,
      role: demoStudent.role,
      department: demoStudent.department,
      assignedClasses: demoStudent.assignedClasses,
      isDemo: true,
      authType: 'DEMO_QR',
      demoGeneration: session.generation,
    },
    demoGeneration: session.generation,
    expiresAt: session.expiresAt,
  }
}

/**
 * Resets the demo presentation environment:
 * 1. Increments global demo generation version.
 * 2. Revokes all existing demo sessions and QR credentials.
 * 3. Broadcasts Socket.IO event to kick active student clients.
 * 4. Generates a brand new QR credential.
 *
 * @param {Object} adminUser - Authenticated Super Admin user object
 * @returns {Promise<Object>} Brand new QR credential
 */
async function resetDemoSessions(adminUser) {
  const currentGen = await getCurrentDemoGeneration()
  const nextGen = currentGen + 1

  // 1. Atomically advance global demo generation in MongoDB
  await DemoState.findOneAndUpdate(
    { key: 'GLOBAL_DEMO_STATE' },
    {
      $set: {
        currentGeneration: nextGen,
        lastResetAt: new Date(),
        updatedBy: adminUser._id,
      },
    },
    { upsert: true, new: true }
  )

  // 2. Invalidate in-memory cache
  invalidateGenerationCache(nextGen)

  // 3. Revoke all previous active demo sessions
  await DemoSession.updateMany(
    { isActive: true },
    {
      $set: {
        isActive: false,
        status: DEMO_STATUS.REVOKED,
        revokedAt: new Date(),
        revokedBy: adminUser._id,
      },
    }
  )

  // 4. Generate completely new temporary credential for the new generation
  const rawToken = crypto.randomBytes(32).toString('hex')
  const tokenHash = hashDemoToken(rawToken)
  const tokenPrefix = rawToken.slice(0, 8)
  const expiryMinutes = env.DEMO_QR_EXPIRY_MINUTES || 120
  const expiresAt = new Date(Date.now() + expiryMinutes * 60 * 1000)

  const newSession = await DemoSession.create({
    tokenHash,
    tokenPrefix,
    generation: nextGen,
    isActive: true,
    status: DEMO_STATUS.ACTIVE,
    expiresAt,
    createdBy: adminUser._id,
    scanCount: 0,
  })

  // Update active session pointer
  await DemoState.findOneAndUpdate(
    { key: 'GLOBAL_DEMO_STATE' },
    { $set: { activeSessionId: newSession._id } }
  )

  // 5. Broadcast Socket.IO real-time revocation event
  try {
    const io = getIO()
    if (io) {
      const broadcastPayload = {
        reason: 'DEMO_RESET',
        message: 'The demo presentation session has been reset by the Super Admin.',
        previousGeneration: currentGen,
        newGeneration: nextGen,
        timestamp: new Date().toISOString(),
      }
      io.emit('auth:demo_revoked', broadcastPayload)
      io.emit('demo:revoked', broadcastPayload)
      io.emit('demo:reset', broadcastPayload)
      console.log(`[DemoAuth] 📢 Broadcasted demo revocation to Socket.IO clients (New Gen: ${nextGen})`)
    }
  } catch (socketErr) {
    console.warn(`[DemoAuth] ⚠️ Socket broadcast warning during reset: ${socketErr.message}`)
  }

  // 6. Audit log
  console.log(
    `[DemoAuth] 🔄 Super Admin (${adminUser.email}) performed global demo reset: Generation bumped from ${currentGen} to ${nextGen}. All active demo sessions revoked.`
  )

  const baseUrl = env.DEMO_QR_BASE_URL || 'http://localhost:5173'
  const qrUrl = `${baseUrl.replace(/\/+$/, '')}/demo-login/${rawToken}`

  // Cache in memory for immediate display on status check
  currentActiveDemoToken = {
    token: rawToken,
    qrUrl,
    generation: nextGen,
    expiresAt,
  }

  return {
    qrUrl,
    token: rawToken,
    tokenPrefix: `${tokenPrefix}...`,
    generation: nextGen,
    expiresAt,
    expiresInMinutes: expiryMinutes,
    status: DEMO_STATUS.ACTIVE,
    isActive: true,
    createdAt: newSession.createdAt,
    previousGeneration: currentGen,
  }
}

/**
 * Retrieves current demo management telemetry and active QR status.
 *
 * @returns {Promise<Object>}
 */
async function getDemoStatus() {
  const currentGen = await getCurrentDemoGeneration()

  const activeSession = await DemoSession.findOne({
    generation: currentGen,
    isActive: true,
    status: DEMO_STATUS.ACTIVE,
  }).sort({ createdAt: -1 })

  const isExpired = activeSession ? activeSession.expiresAt <= new Date() : false
  const remainingSeconds =
    activeSession && !isExpired
      ? Math.max(0, Math.floor((activeSession.expiresAt.getTime() - Date.now()) / 1000))
      : 0

  const hasCachedToken =
    currentActiveDemoToken &&
    currentActiveDemoToken.generation === currentGen &&
    currentActiveDemoToken.expiresAt > new Date()

  return {
    generation: currentGen,
    hasActiveQr: !!activeSession && !isExpired && !!hasCachedToken,
    qrUrl: hasCachedToken ? currentActiveDemoToken.qrUrl : null,
    session:
      activeSession && !isExpired
        ? {
            id: activeSession._id,
            qrUrl: hasCachedToken ? currentActiveDemoToken.qrUrl : null,
            tokenPrefix: `${activeSession.tokenPrefix}...`,
            generation: activeSession.generation,
            expiresAt: activeSession.expiresAt,
            remainingSeconds,
            status: activeSession.status,
            isActive: activeSession.isActive,
            scanCount: activeSession.scanCount,
            lastScannedAt: activeSession.lastScannedAt,
            createdAt: activeSession.createdAt,
          }
        : null,
    expiryMinutes: env.DEMO_QR_EXPIRY_MINUTES || 120,
    timestamp: new Date().toISOString(),
  }
}

module.exports = {
  hashDemoToken,
  getCurrentDemoGeneration,
  invalidateGenerationCache,
  getOrCreateDemoStudent,
  generateDemoCredential,
  loginWithDemoToken,
  resetDemoSessions,
  getDemoStatus,
}
